version: '3.8'

services:
  # Frontend
  cv-builder:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: cv-builder-app
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5001
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "3"

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    container_name: cv-builder-backend
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/cvbuilder
      - JWT_SECRET=change-this-super-secret-key-in-production-123456789
      - NODE_ENV=production
      - CV_LIFETIME_MINUTES=300 # 24 heures par exemple
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "3"

  # MongoDB
  mongo:
    image: mongo:7
    container_name: cv-builder-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=cvbuilder
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  # Mongo Express - Interface Web MongoDB
  mongo-express:
    image: mongo-express:latest
    container_name: cv-builder-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

volumes:
  mongo-data:
